language: node_js
node_js:
  - "12.4.0"
cache:
directories:
  - node_modules
script:
  - npm test
  - npm run test:coverage
  - npm run build

  deploy:
    provider: pages
    skip_cleanup: true
    github: 3ea3d20f65f1654365f00db33e9c7b9af7a2919c
    local_dir: build
    on: 
      branch: master